### ISSUE TITLE
PR roadmap for release 1

### ISSUE THREAD

**Issue by taylorreiter** [Arcadia-Science/2023-rehgt#17]
PR roadmap:

+ [ ] update R scripts and sync snakefile (#13)
+ [ ] copy over required nextflow files (still need to figure out how I want to do organization...a Snakemake folder & a nextflow folder? everything at root?)
+ [ ] remove eggnog rules and replace with kofamscan in both snakemake and nextflow
+ [ ] (maybe) refactor snakemake file to take command line arguments for databases
+ [ ] (maybe) include an optional download snakefile/nextflow workflow to download all of the required databases (two files for clustered nr blast database, ~two eggnog database files~ kofamscan files, an hmm profile file)
+ [ ] update workflow:
    + [ ] improve labels for HGT candidates
    + [ ] check and make sure donor diversity index is correct
    + [ ] ...other stuff that comes up
+ [ ] documentation PR
+ [ ] Release!
